# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: s3imageupload

plugins:
  - serverless-offline


provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::serverless-upload-qwer1/*"

functions:
  s3upload:
    handler: handler.s3upload
    events:
      - http:
          method: post
          path: s3upload
          cors:
            origins:
              - '*'
            headers:
              - '*'
            allowCredentials: false

resources:
  Resources:
    ImageUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-upload-qwer1
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"